// Generated by scripts/build-esolang-runtimes.mjs --write.
export type WasiInterpreterProfile = {
	readonly id: string;
	readonly folder: string;
	readonly fileName: string;
	readonly sourcePath: string;
	readonly sourcePathPrefix?: string;
	readonly maxSourcePathBytes?: number;
	readonly maxSourceBytes?: number;
	readonly minSourceCharacters?: number;
	readonly command: string;
	readonly args: readonly string[];
	readonly sha256: string;
	readonly bytes: number;
};

export const WASI_INTERPRETERS: Readonly<Record<string, WasiInterpreterProfile>> = {
	BRAINFUCK: {
		id: 'BRAINFUCK',
		folder: 'wasm-brainfuck',
		fileName: 'brainfuck.wasm',
		sourcePath: 'main.bf',
		command: 'bfi',
		args: [],
		sha256: '62c813c99c700d65e05974ec0ad07333c8ca40460330f1f835f28a8cb39657a5',
		bytes: 34467
	},
	BEFUNGE93: {
		id: 'BEFUNGE93',
		folder: 'wasm-befunge93',
		fileName: 'befunge93.wasm',
		sourcePath: 'main.b93',
		sourcePathPrefix: './',
		maxSourcePathBytes: 125,
		command: 'bef',
		args: ['-q'],
		sha256: '0b28bdff5085e98bcec4d30a4a3475f693f0ad6c0194ea083c7d1832d994df81',
		bytes: 47871
	},
	WHITESPACE: {
		id: 'WHITESPACE',
		folder: 'wasm-whitespace',
		fileName: 'whitespace.wasm',
		sourcePath: 'main.ws',
		maxSourceBytes: 65535,
		command: 'whitespace',
		args: [],
		sha256: '916bfbce7eb912b7b4d2f44b6a6c5d9fe9357fdb0ad291333587349708319957',
		bytes: 59324
	},
	MALBOLGE: {
		id: 'MALBOLGE',
		folder: 'wasm-malbolge',
		fileName: 'malbolge.wasm',
		sourcePath: 'main.mal',
		minSourceCharacters: 2,
		command: 'malbolge',
		args: [],
		sha256: '27cc66d75e63524b000b62b1117ad45cb3dabc4885530800175affc40f895840',
		bytes: 16067
	},
	UHMLANG: {
		id: 'UHMLANG',
		folder: 'wasm-uhmlang',
		fileName: 'uhmlang.wasm',
		sourcePath: 'main.um',
		command: 'umjunsik',
		args: [],
		sha256: 'f55e8a41f59654818af1d119d32d604165da369ce3aa269282b90fc319ed96dd',
		bytes: 3017206
	},
	LOLCODE: {
		id: 'LOLCODE',
		folder: 'wasm-lolcode',
		fileName: 'lolcode.wasm',
		sourcePath: 'main.lol',
		command: 'lci',
		args: [],
		sha256: '39cd197d5b8681ee37817f87ac86a07ca692407e0226e78e8470d37b57e0ce64',
		bytes: 837757
	}
};
