// Generated by scripts/sync-wasm-grain.mjs from the pinned upstream Grain release.
export const bundledGrainProfile = {
	profileId: 'grain-0.7.2-jsoo-wasi-v1',
	grainVersion: '0.7.2',
	compilerJavaScript: {
		bytes: 20872240,
		sha256: '0a85cf0120aafd873e41eb901a18090453010f8f819074b77c14e1c359cafd1e'
	},
	compilerStorage: {
		bytes: 3417153,
		sha256: '38cf8c42ed83447287e0bc54c768661a110b7becf1b93bdfdd6da30537c4e289'
	},
	stdlibPack: {
		bytes: 5066092,
		sha256: 'c56e83cbea649be5dd94ce98ae648b8f98e40203761ef7b1ad0a799048ee08eb'
	},
	stdlibStorage: {
		bytes: 1653344,
		sha256: '7180475667a3129821be12aa787f449e58de62b0bb5c0e5472077b73b9e5cafa'
	}
} as const;
export const bundledGrainWorkerReceipt = {
	bytes: 28127,
	sha256: 'c36b478c25f000a9a9ecdb186490cf8fce07ece9b5ac271031aa2e97f75cabab'
} as const;
