// Generated by scripts/sync-wasm-c3.mjs from verified local producer artifacts.
export const bundledC3Profile = {
	profileId: 'c3-0.8.3-wasm32-byte-v1',
	producerManifestSha256: '6cd939ede70a166ae56c92c8978ee7d29a972eb3404262cb926bb370d567a8bb',
	compilerJavaScriptReceipt: {
		bytes: 101743,
		sha256: '2174a9b00c8b412c1162683a232d20af3640336b9abfad5a61af872f7d792e45'
	},
	compilerWasmReceipt: {
		bytes: 39058650,
		sha256: 'f84c768a8dcd679bf092b7cd7bb9ec5786bc70bedc9d8929cfbb2d79291d8c0e'
	},
	producerReceipt: {
		bytes: 13996,
		sha256: '3fec378b171e717bf08f5096291740fa313649e14280d156d0cf7cdcf50082f8'
	}
} as const;
export const bundledC3WorkerReceipt = {
	bytes: 14151,
	sha256: '358ee8aabac7e05c9eff87fcf3335410cc189e50b7fe9fc70bd318d9a90b1d56'
} as const;
