// Generated by scripts/sync-wasm-awk.mjs. Do not edit.
export const WASM_AWK_RUNTIME_PROFILE = Object.freeze({
	profileId: 'goawk-v1.31.0-go1.25.3',
	goVersion: 'go1.25.3',
	goawkVersion: 'v1.31.0',
	manifestFingerprint: '73f047e9cc32fea4d353f5f77da9137dd16c0c5196b512475f55bb25ea5a4e43',
	manifestReceipt: Object.freeze({
		bytes: 887,
		sha256: '82b7da83f543cbf22eead6920b09901e61b98f7afa26f9004b937e6ab42843e6'
	}),
	workerReceipt: Object.freeze({
		bytes: 14124,
		sha256: '4a199657d6d56f8626b4c67cbed3219e7852db8152743758968693553ef8c75e'
	}),
	goShimReceipt: Object.freeze({
		bytes: 16992,
		sha256: '0c949f4996f9a89698e4b5c586de32249c3b69b7baadb64d220073cc04acba14'
	}),
	wasmReceipt: Object.freeze({
		bytes: 1289352,
		sha256: '1e152f3ecfc0e5f66820c8e08987ab9a05d594968ac6af500e93a8a556a2d86e',
		uncompressedBytes: 4697052,
		uncompressedSha256: '04ea6a3b3024ce6c4fd779a620eb5569a23879fb8fe2afaac87103ea7dd4b7a6'
	})
});
export const WASM_AWK_RUNTIME_BUNDLE = Object.freeze({
	profile: WASM_AWK_RUNTIME_PROFILE,
	workerReceipt: WASM_AWK_RUNTIME_PROFILE.workerReceipt
});
export const WASM_AWK_ASSET_VERSION = WASM_AWK_RUNTIME_PROFILE.manifestFingerprint;
export const WASM_AWK_RUNNER_RECEIPT = WASM_AWK_RUNTIME_PROFILE.workerReceipt;
