#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "--help" ]]; then
  cat <<'EOF'
Usage: scripts/prepare-wasip3-libc-overlay.sh

Prepare a cargo config overlay that patches the Rust source build to use a newer libc crate
when building wasm32-wasip3.

Environment:
  WASM_RUST_CUSTOM_TOOLCHAIN_ROOT        Root used to place the prepared overlay
  WASM_RUST_REAL_RUSTC_ROOT              Fallback root when CUSTOM_TOOLCHAIN_ROOT is unset
  WASM_RUST_RUST_SOURCE_ROOT             Rust checkout used to infer the locked libc version
  WASM_RUST_WASIP3_LIBC_VERSION          libc source version to materialize (default: 0.2.183)
  WASM_RUST_WASIP3_LIBC_PATCH_VERSION    libc package version written into the overlay
  WASM_RUST_WASIP3_LIBC_SOURCE           Explicit source directory for the libc crate
  WASM_RUST_CARGO_REGISTRY_SRC_ROOT      Override cargo registry src root to search first
  WASM_RUST_BASE_CARGO_HOME              Base cargo home to mirror caches from
  WASM_RUST_WASIP3_OVERLAY_ROOT          Override overlay root directory
  WASM_RUST_WASIP3_CARGO_HOME            Override cargo home written for the patched build
  WASM_RUST_WASIP3_LIBC_DOWNLOAD_URL     Override the crates.io download URL when cache lookup misses

The script prints KEY=VALUE lines for:
  WASM_RUST_WASIP3_LIBC_PATCH_SOURCE
  WASM_RUST_WASIP3_CARGO_HOME
EOF
  exit 0
fi

if [[ $# -gt 0 ]]; then
  printf 'unsupported argument: %s\n' "${1:-}" >&2
  exit 2
fi

root="${WASM_RUST_CUSTOM_TOOLCHAIN_ROOT:-${WASM_RUST_REAL_RUSTC_ROOT:-$HOME/.cache/wasm-rust-custom-toolchain}}"
rust_root="${WASM_RUST_RUST_SOURCE_ROOT:-$root/rust}"
source_libc_version="${WASM_RUST_WASIP3_LIBC_VERSION:-0.2.183}"
patch_libc_version="${WASM_RUST_WASIP3_LIBC_PATCH_VERSION:-}"
base_cargo_home="${WASM_RUST_BASE_CARGO_HOME:-${CARGO_HOME:-$HOME/.cargo}}"
registry_src_root="${WASM_RUST_CARGO_REGISTRY_SRC_ROOT:-$base_cargo_home/registry/src}"
overlay_root="${WASM_RUST_WASIP3_OVERLAY_ROOT:-$root/wasip3-libc-overlay}"
patched_cargo_home="${WASM_RUST_WASIP3_CARGO_HOME:-$overlay_root/cargo-home}"
download_url="${WASM_RUST_WASIP3_LIBC_DOWNLOAD_URL:-https://static.crates.io/crates/libc/libc-$source_libc_version.crate}"
source_path="${WASM_RUST_WASIP3_LIBC_SOURCE:-}"

if [[ -z "$patch_libc_version" ]]; then
  for lock_path in \
    "$rust_root/Cargo.lock" \
    "$rust_root/library/Cargo.lock" \
    "$rust_root/src/bootstrap/Cargo.lock"
  do
    if [[ ! -f "$lock_path" ]]; then
      continue
    fi
    patch_libc_version="$(
      awk '
        /^\[\[package\]\]$/ { package_name = ""; next }
        /^name = "libc"$/ { package_name = "libc"; next }
        package_name == "libc" && /^version = "/ {
          sub(/^version = "/, "", $0)
          sub(/"$/, "", $0)
          print
          exit
        }
      ' "$lock_path"
    )"
    if [[ -n "$patch_libc_version" ]]; then
      break
    fi
  done
fi
if [[ -z "$patch_libc_version" ]]; then
  patch_libc_version="$source_libc_version"
fi

patched_libc_path="$overlay_root/libc-$patch_libc_version"

mkdir -p "$overlay_root"

if [[ -z "$source_path" && -d "$registry_src_root" ]]; then
  while IFS= read -r candidate; do
    source_path="$candidate"
    break
  done < <(find "$registry_src_root" -maxdepth 2 -type d -name "libc-$source_libc_version" | sort)
fi

if [[ -z "$source_path" ]]; then
  download_dir="$overlay_root/download/libc-$source_libc_version"
  crate_path="$overlay_root/download/libc-$source_libc_version.crate"
  rm -rf "$download_dir"
  mkdir -p "$download_dir"
  curl -LfsS "$download_url" -o "$crate_path"
  tar -xzf "$crate_path" -C "$download_dir"
  if [[ -f "$download_dir/Cargo.toml" ]]; then
    source_path="$download_dir"
  else
    while IFS= read -r candidate; do
      source_path="$candidate"
      break
    done < <(find "$download_dir" -maxdepth 2 -type f -name Cargo.toml | sort | xargs -r -n1 dirname)
  fi
fi

if [[ ! -f "$source_path/Cargo.toml" ]]; then
  printf 'missing Cargo.toml for wasm32-wasip3 libc source at %s\n' "$source_path" >&2
  exit 1
fi

if [[ "$source_path" != "$patched_libc_path" ]]; then
  rm -rf "$patched_libc_path"
  mkdir -p "$patched_libc_path"
  cp -R "$source_path"/. "$patched_libc_path"/
fi

if [[ "$patch_libc_version" != "$source_libc_version" ]]; then
  perl -0pi -e 's/(\[package\]\n(?:[^\n]*\n)*?name = "libc"\nversion = ")[^"]+(")/${1}'"$patch_libc_version"'${2}/s' \
    "$patched_libc_path/Cargo.toml"
  if [[ -f "$patched_libc_path/Cargo.toml.orig" ]]; then
    perl -0pi -e 's/(\[package\]\n(?:[^\n]*\n)*?name = "libc"\nversion = ")[^"]+(")/${1}'"$patch_libc_version"'${2}/s' \
      "$patched_libc_path/Cargo.toml.orig"
  fi
fi

mkdir -p "$patched_cargo_home"
cat > "$patched_cargo_home/config.toml" <<EOF
# generated by wasm-rust/scripts/prepare-wasip3-libc-overlay.sh
[patch.crates-io]
libc = { path = "$patched_libc_path" }
EOF

for mirrored_entry in registry git bin credentials credentials.toml .crates.toml .crates2.json; do
  source_entry="$base_cargo_home/$mirrored_entry"
  target_entry="$patched_cargo_home/$mirrored_entry"
  if [[ -e "$source_entry" && ! -e "$target_entry" ]]; then
    ln -s "$source_entry" "$target_entry"
  fi
done

printf 'WASM_RUST_WASIP3_LIBC_PATCH_SOURCE=%s\n' "$patched_libc_path"
printf 'WASM_RUST_WASIP3_CARGO_HOME=%s\n' "$patched_cargo_home"
