// Generated by scripts/sync-wasm-teavm.mjs. Do not edit.

export const TEAVM_ASSET_VERSION =
	'05b4ac88a7a71e2f8aee11cceed55f8d671a2fae77fc15e2e2ed413f3fccbb28';

export const TEAVM_ASSET_RECEIPTS = Object.freeze({
	'compiler.wasm-runtime.js': Object.freeze({
		bytes: 13936,
		sha256: 'bd103f277be99fd2f3ffc0248b3558e6c2c85a44902bfeef042c6bedcf0b2c63'
	}),
	'compiler.wasm': Object.freeze({
		bytes: 4299273,
		sha256: '9eb047426613c3ed3006838daae49e29929ad0d560ec6b1f8b50e15e2c3865d6'
	}),
	'compile-classlib-teavm.bin': Object.freeze({
		bytes: 200621,
		sha256: '71746dc82ddad5ad8be829f461c235a747bdaf121d1b7abd16dbbbbe6a17f53d'
	}),
	'runtime-classlib-teavm.bin': Object.freeze({
		bytes: 2394175,
		sha256: 'f0c9c8c0426e310d08751e57cc88fdfd63ea2f428e4d6cb1b7e59a3dc20844ad'
	})
});
