// Generated by scripts/sync-wasm-haskell.mjs. Do not edit.
export const HASKELL_RUNTIME_GENERATED_ASSET_VERSION =
	'ad4051158177810dbfedd9293ff0fd62ec898399f5f558d0fc420a94ff0ba6cb' as const;
export const HASKELL_RUNTIME_GENERATED_ASSET_RECEIPTS = Object.freeze({
	'dyld.mjs': Object.freeze({
		bytes: 82322,
		sha256: 'cc1835b8530f71e29727a71648b635a5cf28f46ed84451f2de17b194d60033d4'
	}),
	'rootfs.tar.zst': Object.freeze({
		bytes: 49091550,
		sha256: '35f68f56fdb72111f150ba05ad31efed2f6fc77ee7026fb4b197ae7901a67adf'
	}),
	'bsdtar.wasm': Object.freeze({
		bytes: 1240004,
		sha256: 'e13ebb15ca0971f6629a6313bc043c532dd9be3a0e6bb0b7f8a395de835ad0c0'
	})
});
