// Generated by scripts/sync-wasm-haskell.mjs. Do not edit.
export const HASKELL_RUNTIME_GENERATED_ASSET_VERSION =
	'5c94c1aaaf5ad41bf472a4766bfb155982d8e59a160ae610a90928230867efb8' as const;
export const HASKELL_RUNTIME_GENERATED_ASSET_RECEIPTS = Object.freeze({
	'dyld.mjs': Object.freeze({
		bytes: 83177,
		sha256: 'd2260e7669868741fde2f1ba8cd38a9d63bff532c8ccb53d18b210b60af915d9'
	}),
	'rootfs.tar.zst': Object.freeze({
		bytes: 49091550,
		sha256: '35f68f56fdb72111f150ba05ad31efed2f6fc77ee7026fb4b197ae7901a67adf'
	}),
	'bsdtar.wasm': Object.freeze({
		bytes: 1240004,
		sha256: 'e13ebb15ca0971f6629a6313bc043c532dd9be3a0e6bb0b7f8a395de835ad0c0'
	})
});
