// Generated by scripts/sync-wasm-ruby-split.mjs from verified npm inputs.
const freeze = <T>(value: T): Readonly<T> => { if(value && typeof value === 'object') { for(const child of Object.values(value)) freeze(child); Object.freeze(value); } return value; };
export const RUBY_SPLIT_BUNDLE = freeze({
  "profileId": "ruby-3.4.1-ruby-wasm-2.9.3-2.9.4-split-stdlib-v1",
  "version": "a6e2d91fdb9c4f33dc443d6c94195ec3d9d11369fa434ebc17ff6e1c35c09cac",
  "manifest": {
    "path": "runtime-split.v1.json",
    "bytes": 4304,
    "sha256": "a6e2d91fdb9c4f33dc443d6c94195ec3d9d11369fa434ebc17ff6e1c35c09cac"
  },
  "mountPaths": [
    "/usr",
    "/usr/local",
    "/usr/local/lib",
    "/usr/local/lib/ruby",
    "/usr/local/lib/ruby/3.4.0",
    "/usr/local/lib/ruby/gems",
    "/usr/local/lib/ruby/gems/3.4.0",
    "/bundle"
  ],
  "assets": {
    "module": {
      "path": "runtime.mjs.bin",
      "encoding": "identity",
      "bytes": 54623,
      "sha256": "d832ed230a34df7db0a7ed823d4fc974fb532b532e0b0de0ad76033acec05b71",
      "logicalBytes": 54623,
      "logicalSha256": "d832ed230a34df7db0a7ed823d4fc974fb532b532e0b0de0ad76033acec05b71"
    },
    "wasm": {
      "path": "ruby-core.wasm.gz.bin",
      "encoding": "gzip",
      "bytes": 5048770,
      "sha256": "116edf97a5fbe0ec4451692ae3c0b03157e8e9b8979fee1e3c2b226eb11c511a",
      "logicalBytes": 16626499,
      "logicalSha256": "0b8058bf32efd1edb51f5c2116d19c7680e07884fafa6b37ceb49212fee96152"
    },
    "stdlib": {
      "path": "stdlib.pack.gz.bin",
      "encoding": "gzip",
      "bytes": 4016901,
      "sha256": "3fba398455d2e32eb847906c3d9a2c616c45ece5620477739766b1222b8f1fc1",
      "logicalBytes": 14791446,
      "logicalSha256": "245a8cae10b581a1119d8b9ab6f993b447d31828a483d69a210d4d5e03c2d7b9"
    }
  }
} as const);
