// Generated by scripts/sync-wasm-ruby.mjs. Do not edit.
export const RUBY_RUNTIME_GENERATED_ASSET_PATH = 'assets/ruby_stdlib-C40Yu-vu.wasm' as const;
export const RUBY_RUNTIME_GENERATED_ASSET_VERSION =
	'0bac7e15f390f20cccaa1d422a8fd76cb57c0dea3a4ca4e404a4dd529a98906c' as const;
export const RUBY_RUNTIME_GENERATED_ASSET_RECEIPTS = Object.freeze({
	'runtime.mjs': Object.freeze({
		bytes: 54623,
		sha256: 'd832ed230a34df7db0a7ed823d4fc974fb532b532e0b0de0ad76033acec05b71' as const
	}),
	[RUBY_RUNTIME_GENERATED_ASSET_PATH]: Object.freeze({
		bytes: 30608059,
		sha256: '81bc8bbb2130ea34f30826e03d850661bb6cb1c7fe72be598584f12b2810c9de' as const
	})
});
