// Generated by scripts/sync-wasm-ruby.mjs. Do not edit.
export const RUBY_RUNTIME_GENERATED_PROFILE = Object.freeze({
	profileId: 'ruby-3.4.1-ruby-wasm-2.10.1' as const,
	artifactRevision: 'c7151435f55e1f078ca823231593f56e6a855873' as const,
	rubyVersion: '3.4.1' as const,
	rubyRevision: '48d4efcb85000e1ebae42004e963b5d0cedddcf2' as const,
	rubyWasmVersion: '2.10.1' as const,
	rubyWasmRevision: 'c7151435f55e1f078ca823231593f56e6a855873' as const,
	wasiSdkVersion: '22.0' as const,
	manifestFingerprint:
		'45146a821c16192efe93ed2b16ce30e73716fc83d2e437d2fdb9dd6dac78b37b' as const,
	manifestReceipt: Object.freeze({
		bytes: 7782,
		sha256: '4e5f21e2835571078893032f47775460e74722994d906c2983f0621864b6a5e0' as const
	}),
	moduleJavaScriptReceipt: Object.freeze({
		bytes: 54866,
		sha256: 'd1d33ccf090d3e99d8e3fd54a4e18c258d468e101711d0aee360e51dc2e26fd9' as const
	}),
	wasmReceipt: Object.freeze({
		bytes: 9058728,
		sha256: '7fd753e801bf2cc58111149d8c77539b941480e848274b51a39c4dcef2d2bb13' as const,
		uncompressedBytes: 30635497,
		uncompressedSha256:
			'4b814fc9d13505ea5b4c1f3bd3a7cc7ccca137f551196b9b21f0a7caf9cc5878' as const
	})
});
export const RUBY_RUNTIME_GENERATED_BUNDLE = Object.freeze({
	profile: RUBY_RUNTIME_GENERATED_PROFILE
});
export const RUBY_RUNTIME_GENERATED_ASSET_PATH = 'assets/ruby_stdlib-D8-A_OuU.wasm' as const;
export const RUBY_RUNTIME_GENERATED_ASSET_VERSION =
	RUBY_RUNTIME_GENERATED_PROFILE.manifestFingerprint;
export const RUBY_RUNTIME_GENERATED_ASSET_RECEIPTS = Object.freeze({
	'runtime.mjs': RUBY_RUNTIME_GENERATED_PROFILE.moduleJavaScriptReceipt,
	[RUBY_RUNTIME_GENERATED_ASSET_PATH]: Object.freeze({
		bytes: RUBY_RUNTIME_GENERATED_PROFILE.wasmReceipt.uncompressedBytes,
		sha256: RUBY_RUNTIME_GENERATED_PROFILE.wasmReceipt.uncompressedSha256
	})
});
