// Generated by scripts/sync-wasm-ruby.mjs. Do not edit.
export const RUBY_RUNTIME_GENERATED_PROFILE = Object.freeze({
	profileId: 'ruby-3.4.1-ruby-wasm-2.9.3-2.9.4' as const,
	artifactRevision: '3318796e2c9f0f75c98c669cabdc422cf8218ec2' as const,
	rubyVersion: '3.4.1' as const,
	rubyRevision: '48d4efcb85000e1ebae42004e963b5d0cedddcf2' as const,
	rubyWasmVersion: '2.9.3-2.9.4' as const,
	rubyWasmRevision: '3318796e2c9f0f75c98c669cabdc422cf8218ec2' as const,
	wasiSdkVersion: '22.0' as const,
	manifestFingerprint:
		'e8b1ff472882d0580a235bf31715b699fbb70d75d09ad0dc88b19ba7f42d9ed2' as const,
	manifestReceipt: Object.freeze({
		bytes: 7832,
		sha256: '0f0c0cdb2548aebde61e0a2cb9b8d899ce5a4b51b9a21aac9bd96555fc46fe0a' as const
	}),
	moduleJavaScriptReceipt: Object.freeze({
		bytes: 54623,
		sha256: 'd832ed230a34df7db0a7ed823d4fc974fb532b532e0b0de0ad76033acec05b71' as const
	}),
	wasmReceipt: Object.freeze({
		bytes: 9051961,
		sha256: '4bffd8398d79eed9e5bbe7cd809a88bd3cb861642054a6f3d63b2abfa80f3030' as const,
		uncompressedBytes: 30608059,
		uncompressedSha256:
			'81bc8bbb2130ea34f30826e03d850661bb6cb1c7fe72be598584f12b2810c9de' as const
	})
});
export const RUBY_RUNTIME_GENERATED_BUNDLE = Object.freeze({
	profile: RUBY_RUNTIME_GENERATED_PROFILE
});
export const RUBY_RUNTIME_GENERATED_ASSET_PATH = 'assets/ruby_stdlib-C40Yu-vu.wasm' as const;
export const RUBY_RUNTIME_GENERATED_ASSET_VERSION =
	RUBY_RUNTIME_GENERATED_PROFILE.manifestFingerprint;
export const RUBY_RUNTIME_GENERATED_ASSET_RECEIPTS = Object.freeze({
	'runtime.mjs': RUBY_RUNTIME_GENERATED_PROFILE.moduleJavaScriptReceipt,
	[RUBY_RUNTIME_GENERATED_ASSET_PATH]: Object.freeze({
		bytes: RUBY_RUNTIME_GENERATED_PROFILE.wasmReceipt.uncompressedBytes,
		sha256: RUBY_RUNTIME_GENERATED_PROFILE.wasmReceipt.uncompressedSha256
	})
});
