// Generated by scripts/sync-wasm-ruby-split.mjs from verified npm inputs.
const freeze = <T>(value: T): Readonly<T> => { if(value && typeof value === 'object') { for(const child of Object.values(value)) freeze(child); Object.freeze(value); } return value; };
export const RUBY_SPLIT_BUNDLE = freeze({
  "profileId": "ruby-3.4.1-ruby-wasm-2.10.1-split-stdlib-v1",
  "version": "57880188dbfe3299bc9932e1136e56cf9591ee07b1556dbcd85afd5fd8e80907",
  "manifest": {
    "path": "runtime-split.v1.json",
    "bytes": 4259,
    "sha256": "57880188dbfe3299bc9932e1136e56cf9591ee07b1556dbcd85afd5fd8e80907"
  },
  "mountPaths": [
    "/usr",
    "/usr/local",
    "/usr/local/lib",
    "/usr/local/lib/ruby",
    "/usr/local/lib/ruby/3.4.0",
    "/usr/local/lib/ruby/gems",
    "/usr/local/lib/ruby/gems/3.4.0",
    "/bundle"
  ],
  "assets": {
    "module": {
      "path": "runtime.mjs.bin",
      "encoding": "identity",
      "bytes": 54866,
      "sha256": "d1d33ccf090d3e99d8e3fd54a4e18c258d468e101711d0aee360e51dc2e26fd9",
      "logicalBytes": 54866,
      "logicalSha256": "d1d33ccf090d3e99d8e3fd54a4e18c258d468e101711d0aee360e51dc2e26fd9"
    },
    "wasm": {
      "path": "ruby-core.wasm.gz.bin",
      "encoding": "gzip",
      "bytes": 5050303,
      "sha256": "d427b86c2bb221bd007731795d44212bd1d61a3bc58661ab78276906b30a491b",
      "logicalBytes": 16655034,
      "logicalSha256": "e64fa4c82cbbb62044648b0a15b96f3486ff3ecbab7bb7a3df11b4ee3e907ddc"
    },
    "stdlib": {
      "path": "stdlib.pack.gz.bin",
      "encoding": "gzip",
      "bytes": 4016936,
      "sha256": "49887b7d427526bd04045b2da56895c51c9824c1681bbdbd2bf4ca5cc2cbbf5b",
      "logicalBytes": 14791924,
      "logicalSha256": "db6419553b4e2773999d48d4e3a7d4b5f750faed01171f5ec72f4772bbb2f5d8"
    }
  }
} as const);
