#!/usr/bin/env node
import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const receiptFor = (bytes) => ({ bytes: bytes.length, sha256: sha256(bytes) });
const expectedManifest = '6cd939ede70a166ae56c92c8978ee7d29a972eb3404262cb926bb370d567a8bb';

/** Publish an already-verified bundle and its generated profile with rollback on publication failure.
 * @param {{ targetDir: string; versionModulePath: string; files: Record<string, Uint8Array>; version: string }} options
 */
export async function publishC3Bundle({ targetDir, versionModulePath, files, version }) {
	targetDir = path.resolve(targetDir);
	versionModulePath = path.resolve(versionModulePath);
	const staging = `${targetDir}.staging-${randomUUID()}`;
	const backup = `${targetDir}.backup-${randomUUID()}`;
	const stagedVersion = `${versionModulePath}.staging-${randomUUID()}`;
	await mkdir(path.dirname(targetDir), { recursive: true });
	await mkdir(staging);
	let moved = false;
	let published = false;
	let complete = false;
	try {
		for (const [name, bytes] of Object.entries(files)) {
			await writeFile(path.join(staging, name), bytes, { flag: 'wx' });
			if (sha256(await readFile(path.join(staging, name))) !== sha256(bytes)) {
				throw new Error(`C3 copied asset changed: ${name}`);
			}
		}
		await mkdir(path.dirname(versionModulePath), { recursive: true });
		await writeFile(stagedVersion, version, { flag: 'wx' });
		try {
			await rename(targetDir, backup);
			moved = true;
		} catch (error) {
			if (!(error instanceof Error) || !('code' in error) || error.code !== 'ENOENT') {
				throw error;
			}
		}
		await rename(staging, targetDir);
		published = true;
		await rename(stagedVersion, versionModulePath);
		complete = true;
	} catch (error) {
		if (published) await rm(targetDir, { recursive: true, force: true });
		if (moved) await rename(backup, targetDir);
		throw error;
	} finally {
		await rm(staging, { recursive: true, force: true });
		await rm(stagedVersion, { force: true });
		if (complete && moved) await rm(backup, { recursive: true });
	}
}

/** The producer path is an explicitly supplied trusted local checkout, never a runtime URL. */
export async function syncC3(producer) {
	const producerRoot = path.resolve(producer);
	const directory = path.join(producerRoot, 'out/c3-browser');
	const { verify } = await import(
		pathToFileURL(path.join(producerRoot, 'producer/c3-browser/scripts/package.mjs')).href
	);
	const receipt = await verify(directory);
	if (
		receipt.manifestSha256 !== expectedManifest ||
		receipt.sources.c3.commit !== '1d155ee04d3b607261b99aa15ed5eefd6d7db284'
	) {
		throw new Error('C3 producer revision is not the reviewed 0.8.3 profile');
	}
	const files = {};
	for (const name of ['c3c.mjs', 'c3c.wasm', 'producer-receipt.json']) {
		files[name] = await readFile(path.join(directory, name));
		if (
			name !== 'producer-receipt.json' &&
			JSON.stringify(receiptFor(files[name])) !== JSON.stringify(receipt.assets[name])
		) {
			throw new Error(`C3 producer asset changed during sync: ${name}`);
		}
	}
	if (JSON.stringify(JSON.parse(files['producer-receipt.json'])) !== JSON.stringify(receipt)) {
		throw new Error('C3 producer receipt changed during sync');
	}
	const profile = {
		profileId: 'c3-0.8.3-wasm32-byte-v1',
		producerManifestSha256: expectedManifest,
		compilerJavaScriptReceipt: receiptFor(files['c3c.mjs']),
		compilerWasmReceipt: receiptFor(files['c3c.wasm']),
		producerReceipt: receiptFor(files['producer-receipt.json'])
	};
	const memory = await readFile(path.join(root, 'scripts/runtime-workers/c3-memory.mjs'), 'utf8');
	const worker = await readFile(
		path.join(root, 'scripts/runtime-workers/wasm-c3-runner-worker.js'),
		'utf8'
	);
	if (worker.split('__WASM_IDLE_C3_PROFILE__').length !== 2)
		throw new Error('C3 worker profile placeholder must occur exactly once');
	files['runner-worker.js'] = Buffer.from(
		memory.replace(/^export /gm, '') +
			'\n' +
			worker.replace('__WASM_IDLE_C3_PROFILE__', JSON.stringify(profile))
	);
	const target = path.join(root, 'static/wasm-c3');
	const versionModulePath = path.join(root, 'src/lib/playground/wasmC3Version.ts');
	const { format, resolveConfig } = await import('prettier');
	const version = await format(
		'// Generated by scripts/sync-wasm-c3.mjs from verified local producer artifacts.\n' +
			`export const bundledC3Profile = ${JSON.stringify(profile, null, '\t')} as const;\n` +
			`export const bundledC3WorkerReceipt = ${JSON.stringify(receiptFor(files['runner-worker.js']), null, '\t')} as const;\n`,
		{ ...(await resolveConfig(versionModulePath)), parser: 'typescript' }
	);
	await publishC3Bundle({ targetDir: target, versionModulePath, files, version });
	console.log(`Synced verified C3 compiler and consumer worker to ${target}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	const [flag, producer, ...extra] = process.argv.slice(2);
	if (flag !== '--producer' || !producer || extra.length)
		throw new Error('Usage: sync-wasm-c3.mjs --producer /absolute/path/to/wasm-llvm');
	await syncC3(producer);
}
