export const enum SourceLanguage {
    TEXT = 'TEXT',
    C = 'C',
    C99 = 'C99',
    C11 = 'C11',
    C18 = 'C18',
    CPP = 'CPP',
    CPP03 = 'CPP03',
    CPP11 = 'CPP11',
    CPP14 = 'CPP14',
    CPP17 = 'CPP17',
    CPP20 = 'CPP20',
    CPP23 = 'CPP23',
    CPP26 = 'CPP26',
    PYTHON3 = 'PYTHON3',
    PYPY3 = 'PYPY3',
    JAVA = 'JAVA',
    JAVA8 = 'JAVA8',
    JAVA11 = 'JAVA11',
    JAVA15 = 'JAVA15',
    JAVASCRIPT = 'JAVASCRIPT',
    TYPESCRIPT = 'TYPESCRIPT',
    GO = 'GO',
    RUST = 'RUST',
    RUST2018 = 'RUST2018',
    RUST2021 = 'RUST2021',
    RUST2024 = 'RUST2024',
    KOTLIN = 'KOTLIN',
    KOTLIN_NATIVE = 'KOTLIN_NATIVE',
    KOTLIN_JAVA = 'KOTLIN_JAVA',
    HASKELL = 'HASKELL',
    OCAML = 'OCAML',
    ELIXIR = 'ELIXIR',
    RUBY = 'RUBY',
    PHP = 'PHP',
    CSHARP = 'CSHARP',
    LUA = 'LUA',
    PERL = 'PERL',
    UHMLANG = 'UHMLANG',
}

export interface SourceFile {
    name: string
    source: string
}
