import { createTinyGoBrowserRuntime, type TinyGoBrowserRuntime } from './runtime'
import './style.css'

const tinygoBootstrapSourcePreview = `/* generated by wasm-tinygo tinygo bootstrap frontend */
/* entry: /workspace/main.go */
/* package-files: 1 */
/* imported-files: 0 */
/* stdlib-files: 0 */
/* all-files: 1 */

static const char *tinygo_package_files[] = {
    "/workspace/main.go",
};

static const char *tinygo_imported_package_files[] = {
    ((const char *)0),
};

static const char *tinygo_stdlib_package_files[] = {
    ((const char *)0),
};

static const char *tinygo_all_compile_files[] = {
    "/workspace/main.go",
};

static const char tinygo_embedded_manifest_json[] = "{\"entryFile\":\"/workspace/main.go\",\"materializedFiles\":[\"/working/.tinygo-root/src/device/arm/arm.go\",\"/working/.tinygo-root/src/runtime/asm_tinygowasm.S\",\"/working/.tinygo-root/src/runtime/gc_boehm.c\",\"/working/.tinygo-root/src/runtime/internal/sys/zversion.go\",\"/working/.tinygo-root/targets/wasm-undefined.txt\",\"/working/.tinygo-root/targets/wasm.json\",\"/working/tinygo-bootstrap.c\",\"/working/tinygo-compile-unit.json\"],\"toolchain\":{\"target\":\"wasm\",\"artifactOutputPath\":\"/working/out.wasm\"},\"sourceSelection\":{\"allCompile\":[\"/workspace/main.go\"]}}";

unsigned int tinygo_embedded_manifest_len(void) {
    return 1350u;
}

const char *tinygo_embedded_manifest_ptr(void) {
    return tinygo_embedded_manifest_json;
}

int main(void) {
    return tinygo_embedded_manifest_len() == 0u ? 1 : 0;
}
`

const driverSource = `package main

import (
    "fmt"
    "os"

    "wasm-tinygo/internal/driver"
    "wasm-tinygo/internal/tinygofrontend"
)

func main() {
    switch os.Getenv("WASM_TINYGO_MODE") {
    case "frontend":
        consumedAnalysis := false
        if _, err := os.Stat("/working/tinygo-frontend-analysis.json"); err == nil {
            consumedAnalysis = true
        }
        if err := tinygofrontend.ExecuteResultPaths("/working/tinygo-frontend-input.json", "/working/tinygo-frontend-analysis.json", "/working/tinygo-frontend-result.json"); err != nil {
            fmt.Println("tinygo frontend failed:", err)
            os.Exit(1)
        }
        if consumedAnalysis {
            fmt.Println("tinygo frontend consuming analysis handoff; tinygo frontend prepared bootstrap compile request")
            break
        }
        fmt.Println("tinygo frontend prepared bootstrap compile request")
    case "frontend-analysis-build":
        if err := tinygofrontend.ExecuteAnalysisBuildPaths("/working/tinygo-frontend-analysis.json", "/working/tinygo-frontend-result.json"); err != nil {
            fmt.Println("tinygo frontend failed:", err)
            os.Exit(1)
        }
        fmt.Println("tinygo frontend consuming analysis handoff; tinygo frontend prepared bootstrap compile request")
    case "frontend-analysis":
        if err := tinygofrontend.ExecuteAnalysisPaths("/working/tinygo-frontend-input.json", "/working/tinygo-frontend-analysis.json"); err != nil {
            fmt.Println("tinygo frontend analysis failed:", err)
            os.Exit(1)
        }
        fmt.Println("tinygo frontend prepared analysis handoff")
    case "frontend-real-adapter":
        if err := tinygofrontend.ExecuteAdapterPaths("/working/tinygo-frontend-input.json", "/working/tinygo-frontend-real-adapter.json"); err != nil {
            fmt.Println("tinygo frontend real adapter failed:", err)
            os.Exit(1)
        }
        fmt.Println("tinygo frontend prepared real adapter handoff")
    default:
        if err := driver.ExecutePaths("/workspace/tinygo-request.json", "/workspace/tinygo-result.json"); err != nil {
            fmt.Println("tinygo driver failed:", err)
            os.Exit(1)
        }
        fmt.Println("tinygo driver planned bootstrap build")
    }
}
`

const html = String.raw
const app = document.querySelector<HTMLDivElement>('#app')

if (!app) {
  throw new Error('App root not found')
}

const escapeHtml = (source: string) =>
  source.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')

app.innerHTML = html`
  <main class="shell">
    <section class="hero panel">
      <div class="eyebrow">Browser Compiler Lab</div>
      <div class="hero-copy">
        <h1>wasm-tinygo</h1>
        <p class="lede">
          emception runtime 위에 브라우저용 TinyGo 포팅 기반을 먼저 세웠습니다.
          현재 단계는 <strong>LLVM/Emscripten 백엔드</strong>와 <strong>Go/WASI 호스트</strong>를
          한 화면에서 검증하는 부트스트랩입니다.
        </p>
      </div>
      <div class="hero-grid">
        <article class="hero-card">
          <span class="card-label">Step 1</span>
          <h2>emception Toolchain</h2>
          <p>브라우저 워커에서 clang, lld, binaryen 기반 파이프라인을 부팅합니다.</p>
        </article>
        <article class="hero-card">
          <span class="card-label">Step 2</span>
          <h2>Build Driver</h2>
          <p>Go/WASI 드라이버가 request/result 계약에 따라 bootstrap build plan을 생성합니다.</p>
        </article>
        <article class="hero-card warning">
          <span class="card-label">Gap</span>
          <h2>TinyGo CLI</h2>
          <p>실제 TinyGo CLI는 아직 미탑재입니다. 브라우저용 빌드 전용 front-end 분리가 다음 단계입니다.</p>
        </article>
      </div>
    </section>

    <section class="workspace">
      <div class="controls panel">
        <div class="section-heading">
          <span class="eyebrow">Control Deck</span>
          <h2>Bootstrap Checks</h2>
        </div>
        <div class="button-row">
          <button data-action="boot" class="action primary">Boot emception</button>
          <button data-action="plan" class="action">Plan TinyGo Build</button>
          <button data-action="execute" class="action">Execute Build Plan</button>
          <button data-action="reset" class="action ghost">Reset Log</button>
        </div>
        <ul class="phase-list">
          <li data-phase="toolchain" data-tone="idle">
            <span class="phase-name">emception worker</span>
            <span class="phase-value">idle</span>
          </li>
          <li data-phase="smoke" data-tone="idle">
            <span class="phase-name">build execution</span>
            <span class="phase-value">idle</span>
          </li>
          <li data-phase="probe" data-tone="idle">
            <span class="phase-name">build driver plan</span>
            <span class="phase-value">idle</span>
          </li>
          <li data-phase="verify" data-tone="idle">
            <span class="phase-name">front-end verification</span>
            <span class="phase-value">idle</span>
          </li>
        </ul>
        <div class="notes">
          <h3>Current scope</h3>
          <p>이 단계부터는 probe가 아니라 request/result 기반 build driver를 브라우저에서 실행합니다.</p>
          <p>1. Go/WASI 드라이버가 build plan을 씁니다.</p>
          <p>2. 브라우저 호스트가 그 plan을 emception으로 실행합니다.</p>
        </div>
      </div>

      <div class="terminal panel">
        <div class="section-heading">
          <span class="eyebrow">Runtime</span>
          <h2>Activity Log</h2>
        </div>
        <pre id="terminal-output" class="terminal-output" aria-live="polite"></pre>
      </div>
    </section>

    <section class="sources">
        <article class="panel source-panel">
        <div class="section-heading">
          <span class="eyebrow">Frontend Output</span>
          <h2>tinygo-bootstrap.c</h2>
        </div>
        <pre><code>${escapeHtml(tinygoBootstrapSourcePreview)}</code></pre>
      </article>
          <article class="panel source-panel">
            <div class="section-heading">
              <span class="eyebrow">Host Probe</span>
              <h2>go-probe/main.go</h2>
            </div>
        <pre><code>${escapeHtml(driverSource)}</code></pre>
          </article>
    </section>
  </main>
`

const terminal = document.querySelector<HTMLPreElement>('#terminal-output')
const bootButton = document.querySelector<HTMLButtonElement>('[data-action="boot"]')
const planButton = document.querySelector<HTMLButtonElement>('[data-action="plan"]')
const executeButton = document.querySelector<HTMLButtonElement>('[data-action="execute"]')
const resetButton = document.querySelector<HTMLButtonElement>('[data-action="reset"]')

if (!terminal || !bootButton || !planButton || !executeButton || !resetButton) {
  throw new Error('UI bindings not found')
}

const setControlsLocked = (locked: boolean) => {
  bootButton.disabled = locked
  planButton.disabled = locked
  executeButton.disabled = locked
  resetButton.disabled = locked
}

const setPhase = (phase: 'toolchain' | 'smoke' | 'probe' | 'verify', label: string, tone: 'idle' | 'running' | 'success' | 'error') => {
  const phaseItem = document.querySelector<HTMLElement>(`[data-phase="${phase}"]`)
  const phaseValue = phaseItem?.querySelector<HTMLElement>('.phase-value')

  if (!phaseItem || !phaseValue) {
    throw new Error(`Phase element missing for ${phase}`)
  }

  phaseItem.dataset.tone = tone
  phaseValue.textContent = label
}

const browserBaseUrl = new URL(import.meta.env.BASE_URL, window.location.href).href
const runtime = createTinyGoBrowserRuntime({
  baseUrl: browserBaseUrl,
  rustRuntimeBaseUrl: new URL('vendor/wasm-rust-runtime/', browserBaseUrl).toString(),
  rustRuntimeAssetPacks: [
    {
      index: 'packs/sysroot/wasm32-wasip1.index.json.gz',
      asset: 'packs/sysroot/wasm32-wasip1.pack.gz',
      fileCount: 30,
      totalBytes: 70715949,
    },
    {
      index: 'packs/link/wasm32-wasip1.index.json.gz',
      asset: 'packs/link/wasm32-wasip1.pack.gz',
      fileCount: 20,
      totalBytes: 51389541,
    },
  ],
  initialLogs: [
    'wasm-tinygo bootstrap ready',
    'Plan the TinyGo build first, then execute the generated plan with emception',
  ],
  onActivityLogChange: (activityLog, tone) => {
    terminal.textContent = activityLog
    terminal.dataset.tone = tone
    terminal.scrollTop = terminal.scrollHeight
  },
  onControlsLockedChange: setControlsLocked,
  onPhaseChange: setPhase,
})

const runUiAction = (run: () => Promise<void>) => {
  void run().catch(() => {})
}

bootButton.addEventListener('click', () => {
  if (bootButton.disabled) {
    return
  }
  runUiAction(async () => {
    await runtime.boot()
  })
})

planButton.addEventListener('click', () => {
  if (planButton.disabled) {
    return
  }
  runUiAction(async () => {
    await runtime.plan()
  })
})

executeButton.addEventListener('click', () => {
  if (executeButton.disabled) {
    return
  }
  runUiAction(async () => {
    await runtime.execute()
  })
})

resetButton.addEventListener('click', () => {
  if (resetButton.disabled) {
    return
  }
  runtime.reset()
})

;(window as Window & { __wasmTinygoTestHooks?: TinyGoBrowserRuntime }).__wasmTinygoTestHooks = runtime
